name: CI

# Indica que el workflow se ejecutará en cada push
on: [push]

jobs:
  build:
    # Define el sistema operativo en el que se ejecutará el job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      # Usa la acción de checkout para clonar el repositorio
      uses: actions/checkout@v2

    - name: Run a one-line script
      # Ejecuta un script simple
      run: echo "Hello, GitHub Actions!"

    - name: Run a multi-line script
      # Ejecuta un script de múltiples líneas
      run: |
        echo "Add other commands here"
        echo "This is a multi-line script"