name: Node.js CI

# Eventos que disparan la ejecución del workflow
on:
  push:
    branches: [main] 
  pull_request:
    branches: [main]  

jobs:
  build:
    runs-on: ubuntu-latest

    # Estrategia para ejecutar el job en diferentes versiones de Node.js
    strategy:
      matrix:
        node-version: [14.x, 16.x]  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Acción para clonar el repositorio

    - name: Setup Node.js
      uses: actions/setup-node@v2  # Acción para configurar Node.js
      with:
        node-version: ${{ matrix.node-version }}  # Usa la versión de Node.js definida en la matriz

    - name: Install dependencies
      run: npm install  # Instala las dependencias del proyecto

    - name: Run tests
      run: npm test  # Ejecuta las pruebas definidas en el proyecto

    - name: Build project
      run: npm run build  # Construye el proyecto

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2  # Acción para subir artefactos generados
      with:
        name: build-artifacts  # Nombre del artefacto
        path: build/  # Ruta de los archivos a subir